In [36]:
import pandas as pd
df = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vQMnws4MzidHka1eo4QmYeriWUazc8Z9iHtEovXmdMJx6qw0pM4Z-8HPh2_y0kRSFfYQ1D2bd3AE3jH/pub?output=csv')

df

,job_title,job_url,job_description
0,"Assistant Elections Manager, Alexandria, Virginia",https://www.governmentjobs.com/careers/alexandria/jobs/5273228/assistant-elections-manager?pagetype=jobOpportunitiesJobs,The City of Alexandria is looking for an Assistant Elections Manager to support election operations and election officer staffing within the City....
1,"Assistant Secretary of State, Mississippi",https://www.sos.ms.gov/content/documents/about_us/Employment/Elections%20ASOS%202026.pdf,The Elections Division has many roles in assuring that Mississippians’ voices are heard clearly through the election process. These roles include ...
2,"Chief Deputy of Elections, Lubbock County, Texas",https://www.governmentjobs.com/careers/colubbocktx/jobs/5266664/chief-deputy-of-elections?pagetype=jobOpportunitiesJobs,"The Chief Deputy assists in managing day-to-day election operations, ensuring compliance with all applicable laws, policies, and regulations. This..."
3,"Deputy Registrar, Richmond, Virginia",https://www.governmentjobs.com/careers/richmond/jobs/5267331/deputy-registrar?keywords=deputy%20registr&pagetype=jobOpportunitiesJobs,The Office of Elections is seeking to hire a candidate for the Deputy Registrar position. This position assists citizens register to vote and assi...
4,"Director of Voter Services, Chester County, Pennsylvania",https://www.governmentjobs.com/careers/chesco/jobs/5287458/director-of-voter-services?pagetype=jobOpportunitiesJobs,"The Director of Voter Services plans, organizes, supervises, and manages the activities of voter registration, campaign finance, and elections for..."
5,"Election Protection Hotline Specialist, Lawyer’s Committee for Civil Rights Under Law",https://lawyerscommitteeforcivilrightsunderlaw.applytojob.com/apply/uHP92PZjul/Election-Protection-Hotline-Specialist?referrer=202602241912374HYTU...,"The Hotline Specialist position is part of our hotline team, which oversees the day-to-day functions of the 866-OUR-VOTE Hotline, as well as provi..."
6,"Election Software Specialist, Printelect",https://www.linkedin.com/jobs/search/?currentJobId=4350549280&f_C=999315&geoId=92000000&origin=COMPANY_PAGE_JOBS_CLUSTER_EXPANSION&originToLanding...,"Printelect is a dynamic and well-established regional election technology & services company with a proven track record in ballot printing, mail s..."
7,"Election Support Aide On-Call, Olmsted County, Minnesota",https://www.governmentjobs.com/careers/olmsted/jobs/5248660/election-support-aide-on-call,"Recognized as one of the best places to work in Southeast Minnesota for three consecutive years, at Olmsted County every role helps to foster a vi..."
8,"Elections Administrator, Lubbock County, Texas",https://www.governmentjobs.com/careers/colubbocktx/jobs/5266832/elections-administrator?page=1&pagetype=jobOpportunitiesJobs,"Appointed by the Lubbock County Election Commission and reporting to the County Judge, the Elections Administrator is responsible for leading and ..."
9,"Elections Specialist, Richmond, Virginia",https://www.governmentjobs.com/careers/richmond/jobs/5267753/elections-specialist?keywords=election%20spe&pagetype=jobOpportunitiesJobs,"The Office of Elections is seeking to hire two Elections Specialists. Incumbents will certify voting machines and ballot machines/scanners, train ..."
10,"Executive Director, Peoria County, Illinois: The Executive Director is responsible for all aspects of the administration of the Election Commissio...","https://peoriacountyil.munisselfservice.com/ess/EmploymentOpportunities/JobDetail.aspx?req=268&sreq=1&form=GNRL&desc=ELECTIONS%20-%20DIRECTOR,%20C...",The Executive Director is responsible for all aspects of the administration of the Election Commission. Duties include the application of all stat...
11,"Sales Engineer I, Hart InterCivic",https://www.hartintercivic.com/jobs/sales-engineer-i/,"The Sales Engineer I is responsible for assisting the Sales Team in generating sales of Hart’s products and services, focusing on expanding existi..."
12,"Senior Policy Analyst, Bipartisan Policy Center",https://workforcenow.adp.com/mascsr/default/mdf/recruitment/recruitment.html?cid=b7ec3708-935d-4824-b8ca-81a1101b34c3&ccId=19000101_000001&lang=en...,"BPC is currently seeking a Senior Policy Analyst to support the work of the Elections Project, which is housed within BPC’s Democracy Program. Th..."
13,"Senior Project Manager, Elections Project, Bipartisan Policy Center",https://workforcenow.adp.com/mascsr/default/mdf/recruitment/recruitment.html?cid=b7ec3708-935d-4824-b8ca-81a1101b34c3&ccId=19000101_000001&lang=en...,"BPC is currently seeking a Project Manager to support the work of the Elections Project, which is housed within BPC’s Governance Program. In the r..."
14,"Voter Services Manager, Richmond, Virginia",https://www.governmentjobs.com/careers/richmond/jobs/5168472/voter-services-manager?keywords=voter&pagetype=jobOpportunitiesJobs,The City of Richmond Office of Elections is seeking a highly organized and knowledgeable Voter Services Manager. The purpose of the position is to...
15,"Voter Services Manager, King County, Washington",https://www.governmentjobs.com/careers/kingcounty/jobs/5215296/voter-services-manager?department[0]=KCE%20-%20King%20County%20Elections&sort=Posit...,"The Voter Services Manager (Elections Program Manager) provides leadership to a dynamic, highly skilled team of supervisors and staff who manage t..."

In [53]:
df.head(2)

,job_title,job_url,job_description
0,"Assistant Elections Manager, Alexandria, Virginia",https://www.governmentjobs.com/careers/alexandria/jobs/5273228/assistant-elections-manager?pagetype=jobOpportunitiesJobs,The City of Alexandria is looking for an Assistant Elections Manager to support election operations and election officer staffing within the City....
1,"Assistant Secretary of State, Mississippi",https://www.sos.ms.gov/content/documents/about_us/Employment/Elections%20ASOS%202026.pdf,The Elections Division has many roles in assuring that Mississippians’ voices are heard clearly through the election process. These roles include ...

In [66]:
title = df.loc[8]['job_description']
title

'Appointed by the Lubbock County Election Commission and reporting to the County Judge, the Elections Administrator is responsible for leading and managing all operations of the Lubbock County Elections Department. This includes oversight of budget, personnel, election systems, and departmental resources, as well as ensuring efficient and secure election processes. The role ensures full compliance with all applicable state and federal election laws, regulations, policies, and procedures, while fostering transparency, integrity, and public trust in the electoral process.'

In [59]:
title.split(',')[0]

'Assistant Elections Manager'

In [ ]:
api_key = "YOUR_OPENWEATHERMAP_API_KEY"
owm = OWM(api_key)
mgr = owm.weather_manager()

def get_weather(city):
    observation = mgr.weather_at_place(city)
    weather = observation.weather
    print(f"Temperature: {weather.temperature('fahrenheit')['temp']}°F")
    print(f"Description: {weather.detailed_status}")

get_weather('Washington,DC,US')

Temperature: 44.85°F
Description: clear sky

In [ ]:
import anthropic
import json
anthropic_api_key = "YOUR_ANTHROPIC_API_KEY"
client = anthropic.Anthropic(api_key=anthropic_api_key)

response = client.messages.create(
    model="claude-opus-4-6",
    max_tokens=1024,
    messages=[
        {
            "role": "user",
            "content": "Extract the key information from this email: John Smith (john@example.com) is interested in our Enterprise plan and wants to schedule a demo for next Tuesday at 2pm.",
        }
    ],
    output_config={
        "format": {
            "type": "json_schema",
            "schema": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "email": {"type": "string"},
                    "plan_interest": {"type": "string"},
                    "demo_requested": {"type": "boolean"},
                },
                "required": ["name", "email", "plan_interest", "demo_requested"],
                "additionalProperties": False,
            },
        }
    },
)
print(response.content[0].text)

{"teachers":"Will Adler, Professor Rachel Orey","coursename":"Using LLMS","university":"Georgetown Law","city":"Washington, D.C."}

In [92]:


def extract_reporting_info(job_description):
    response = client.messages.create(
        model="claude-opus-4-6",
        max_tokens=1024,
        messages=[
            {
                "role": "user",
                "content": (
                    "Extract the following from this job description:\n"
                    "1) who the position reports to\n"
                    "2) the most important responsibility\n\n"
                    "Return only JSON matching the schema.\n\n"
                    "Job description:\n" + job_description
                ),
            }
        ],
        output_config={
            "format": {
                "type": "json_schema",
                "schema": {
                    "type": "object",
                    "properties": {
                        "reports_to": {"type": "string"},
                        "top_responsibility": {"type": "string"},
                    },
                    "required": ["reports_to", "top_responsibility"],
                    "additionalProperties": False,
                },
            }
        },
    )
    text = response.content[0].text
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        raise ValueError(f"Unable to parse structured output: {text}")

# Example usage:
# result = extract_reporting_info(long_job_description)
# print(result)

In [96]:
df.loc[0]['job_description']

'The City of Alexandria is looking for an Assistant Elections Manager to support election operations and election officer staffing within the City. The Assistant Elections Manager’s primary responsibility is to manage elections officer recruitment, placement and training, and help coordinate election day preparation. Responsibilities also include assisting with the management of voting equipment, polling place activities, and the daily operations of absentee voting. The work is performed under the general direction of the Elections Manager.'

In [ ]:
import json
extract_reporting_info(df.loc[0]['job_description'])

{'reports_to': 'Elections Manager',
 'top_responsibility': 'Manage elections officer recruitment, placement and training, and help coordinate election day preparation'}

In [97]:
def safe_extract_reporting_info(description):
    if not isinstance(description, str):
        return {"reports_to": "", "top_responsibility": ""}
    try:
        return extract_reporting_info(description)
    except Exception as e:
        return {"reports_to": "", "top_responsibility": ""}

extracted = df["job_description"].apply(safe_extract_reporting_info)
df["reports_to"] = extracted.map(lambda item: item.get("reports_to", ""))
df["top_responsibility"] = extracted.map(lambda item: item.get("top_responsibility", ""))

df.head()

,job_title,job_url,job_description,reports_to,top_responsibility
0,"Assistant Elections Manager, Alexandria, Virginia",https://www.governmentjobs.com/careers/alexandria/jobs/5273228/assistant-elections-manager?pagetype=jobOpportunitiesJobs,The City of Alexandria is looking for an Assistant Elections Manager to support election operations and election officer staffing within the City....,Elections Manager,"Manage elections officer recruitment, placement and training, and help coordinate election day preparation"
1,"Assistant Secretary of State, Mississippi",https://www.sos.ms.gov/content/documents/about_us/Employment/Elections%20ASOS%202026.pdf,The Elections Division has many roles in assuring that Mississippians’ voices are heard clearly through the election process. These roles include ...,Elections Division,"training election officials, collecting campaign finance and lobbying reports, managing the statewide voter registry, collecting election returns,..."
2,"Chief Deputy of Elections, Lubbock County, Texas",https://www.governmentjobs.com/careers/colubbocktx/jobs/5266664/chief-deputy-of-elections?pagetype=jobOpportunitiesJobs,"The Chief Deputy assists in managing day-to-day election operations, ensuring compliance with all applicable laws, policies, and regulations. This...",Elections Administrator,"Assists in managing day-to-day election operations, ensuring compliance with all applicable laws, policies, and regulations."
3,"Deputy Registrar, Richmond, Virginia",https://www.governmentjobs.com/careers/richmond/jobs/5267331/deputy-registrar?keywords=deputy%20registr&pagetype=jobOpportunitiesJobs,The Office of Elections is seeking to hire a candidate for the Deputy Registrar position. This position assists citizens register to vote and assi...,Office of Elections,Maintaining accurate voter registration records and providing election information and services to candidates and the general public
4,"Director of Voter Services, Chester County, Pennsylvania",https://www.governmentjobs.com/careers/chesco/jobs/5287458/director-of-voter-services?pagetype=jobOpportunitiesJobs,"The Director of Voter Services plans, organizes, supervises, and manages the activities of voter registration, campaign finance, and elections for...",County of Chester,"Plans, organizes, supervises, and manages the activities of voter registration, campaign finance, and elections for the County of Chester in compl..."